## Исключения (#2)

Напишите функцию под названием `abort()`, которая принимает параметр `String`, а затем выбрасывает простой объект `Exception`, передавая аргумент функции `abort()` в конструктор `Exception`. В `main()` вызовите `abort()` с аргументом `"Stop!"` и используйте `capture` для проверки результата.